name: Run Service Every Day

on:
  schedule:
    - cron: "0 9 * * *" # 10 AM Madrid time (CET/UTC+1) equivalent in UTC
  workflow_dispatch:

jobs:
  run-service:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Pull Docker Image
        run: docker pull teresaromero/appointment-availability:1.0

      - name: Run Docker Container
        run: |
          docker run \
            --env HLA_PROVINCE_ID=${{secrets.HLA_PROVINCE_ID}} \
            --env HLA_HEALTH_CENTRE_ID=${{secrets.HLA_HEALTH_CENTRE_ID}} \
            --env HLA_AGREEMENT_ID=${{secrets.HLA_AGREEMENT_ID}} \
            --env HLA_BASE_URL=${{secrets.HLA_BASE_URL}} \
            --env HLA_FORMAT_ID=${{secrets.HLA_FORMAT_ID}} \
            --env HLA_SPECIALTY_ID_LIST=${{secrets.HLA_SPECIALTY_ID_LIST}} \
            --env HLA_USERNAME=${{secrets.HLA_USERNAME}} \
            --env HLA_PASSWORD=${{secrets.HLA_PASSWORD}} \
            --env TG_BOT_APIKEY=${{secrets.TG_BOT_APIKEY}} \
            --env TG_BOT_MASTERID=${{secrets.TG_BOT_MASTERID}} \
            teresaromero/appointment-availability:1.0
